name: actuator
author: vu-ase
source: https://github.com/vu-ase/actuator
version: 1.0.0
description: Controls the motors, servo, lights, and a fan?

commands:
  build: make build 
  run: ./bin/actuator

inputs:
  - service: controller
    streams:
      - decision

outputs: []

configuration:
  - name: i2c-bus
    type: int
    mutable: false
    default: 3

  - name: electronic-diff
    type: int
    mutable: false
    default: 1

  - name: track-width
    type: float
    mutable: false
    default: 60.0

  - name: servo-scaler
    type: float
    mutable: true
    default: 1

  - name: servo-trim
    type: float
    mutable: true
    default: 0

  - name: fan-cap
    type: int
    mutable: false
    default: 100
