# Service definition
name: actuator
description: Controls the motors, servo, lights, and a fan?

# Depends on the controller output
dependencies:
  - service: controller
    output: decision

# No outputs
outputs: []

# Runtime options
options:
  - name: i2c-bus
    type: int
    mutable: false # don't allow OTA changes
    default: 3

  - name: electronic-diff
    type: int
    mutable: false
    default: 1 # 1 is enabled, 0 disabled

  - name: track-width
    type: float
    mutable: false
    default: 60.0

  # This value is used to scale the travel of the servo to its full range.
  # The current value of 1.0 is sufficient for students, however it can be
  # increased/decreased to change range
  - name: servo-scaler
    type: float
    mutable: true
    default: 1

  - name: servo-trim
    type: float
    mutable: true # This value is to be set once and then not updated
    default: 0
    # 0 is center, positive is right, negative is left
  - name: fan-cap
    type: int
    mutable: false
    default: 100 # the fan can spin at 100% speed

 
