name: actuator
author: vu-ase
source: https://github.com/vu-ase/actuator
version: 1.0.0
description: Controls the motors, servo, lights, and a fan?

commands:
  build: make build
  run: ./bin/actuator

inputs:
  - service: controller
    streams:
      - decision

outputs: []

configuration:
  - name: itwoc-bus
    type: number
    mutable: false
    value: 3

  - name: electronic-diff
    type: number
    mutable: false
    value: 1

  - name: track-width
    type: number
    mutable: false
    value: 60

  - name: servo-scaler
    type: number
    mutable: true
    value: 1

  - name: servo-trim
    type: number
    mutable: true
    value: 0

  - name: fan-cap
    type: number
    mutable: false
    value: 100
