name: test
on:
  push:
    branches-ignore:
      - release-please--branches--main

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

jobs:
  test:
    uses: VU-ASE/actions/.github/workflows/test.yaml@main
    secrets:
      gh_pat: ${{ secrets.GH_PAT }}

